version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn tsc:check
      - run: yarn test
      - run: yarn build
  e2e:
    docker:
      - image: cypress/base:14.15.0
    steps:
      - checkout
      - run: node --version
      - run: yarn install
      - run: yarn cypress install
      - run: yarn e2e:ci
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - e2e